### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by adamkarb**

### CODE REVIEW

**Comment by al-the-x** [comment]
Good start, but try to keep the formatting the same as the supplied example.

**Comment by al-the-x** [comment]
Also would prefer a more intentional forking and branching strategy here. Maybe add commits to my branch in your fork and open a PR like this one?

**Comment by adamkarb** [comment]
Yep.  Made that mistake first.  Haven't worked with forked branches so it took a screw up to figure it out

**Comment by al-the-x** [comment]
Congratulations, you're learning!

**Pull request closed without merging**
